name: Build and Deploy React App to CloudFront using Vite

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: braindev1
      DIST: dist
      REGION: us-west-1
      DIST_ID: E2GHSFO0QXH5QF

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install Dependencies
        run: npm install

      - name: Build Static Website using Vite
        run: npm run build

      - name: Upload files to the S3 Bucket
        run: |
          aws s3 sync --delete --acl public-read ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
